import type { Metadata } from "next";
import { Geist, Geist_Mono, Prompt } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar"

const prompt = Prompt({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600"],
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} ${prompt.className} antialiased`}>
        <div className="flex min-h-screen">
         <Sidebar></Sidebar>
         <main className="flex-1 p-4">{children}</main>
        </div>
        
      
      </body>
    </html>
  );
}
